### ISSUE TITLE
Figure out an efficient way of handling docstrings

### ISSUE THREAD

**Issue by ocefpaf** [TEOS-10/python-gsw#5]
> We still have to figure out an efficient way of handling docstrings--something that doesn't require hand-editing a couple hundred chunks of text.  What we have so far is a hodge-podge.  Until we figure out a good mechanism--I have some rough ideas and some helper code--I think the thing to do is just concentrate on the actual function code rather than spend time on editing docstrings.

@efiring I believe that the code you mentioned is this one, correct?

https://github.com/TEOS-10/python-gsw/blob/master/gsw/test/signatures.py

**Comment by ChrisBarker-NOAA** [comment]
Hi - just finding this -- due to a gap in the docstring for gsw.rho() -- it is missing the note about pressure being absolute.

@efiring wrote:
"""
 Presumably it would involve a major docstring generation step as part of python setup.py build, which is unusual.
"""

I wouldn't suggest not doing it in setup.py, but rather, having a separate script that generates the docstrings from the matlab code, and having the generated text committed to the repo. I know it's not generally a good practice to commit generated content, but in this case it's something that needs to be done, and QA/QCd when the matlab code changes -- not really an build/install step.

Anyway, generally sounds like a good plan.

But now I look at Eric's latest post -- it seems you've got a plan like this in mind already!

so a simple note: double check the reference to the pressure parameter for gsw.rho() -- it's missing the reference to absolute pressure.

**Comment by ocefpaf** [comment]
I am closing all issue in TEOS-10/python-gsw now that https://github.com/TEOS-10/GSW-Python is live.
